version: '3.8'
services:
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf

  node_app:
    build:
      context: ./node_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MQTT_HOST: mqtt_broker
      # DB_URL: postgresql://user:password@db:5432/robotdb
    depends_on:
      - mqtt_broker

  # vision_algorithm:
  #   build:
  #     context: ./vision_algorithm
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #     - "8554:8554"
  #   environment:
  #     - RTSP_URL=rtsp://host.docker.internal:8554/mystream
    

    # environment:
    #   - DISPLAY=host.docker.internal:0.0 # Use host.docker.internal to reach the host X server
    # volumes:
    #   - /dev/video0:/dev/video0 # Mount the webcam device (adjust as needed)
    # depends_on:
    #   - db
        
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: robotdb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"